single dimensional array

In [56]:
import numpy as np
n1=np.array([10,20,30,40])
print(n1)

[10 20 30 40]


multi dimensional array

In [57]:
n2=np.array([[10,20,30],
            [40,50,60]])
print(n2)

[[10 20 30]
 [40 50 60]]


initializ numpy array with zeros

In [58]:
n3=np.zeros((1,2))
print(n3)

[[0. 0.]]


In [59]:
n4=np.zeros((3,4))
print(n4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


initializ numpy array with same values

In [60]:
n5=np.full((2,3),10)
print(n5)

[[10 10 10]
 [10 10 10]]


initializ numpy array within a range

In [61]:
n6=np.arange(10,20)
print(n6)

[10 11 12 13 14 15 16 17 18 19]


In [62]:
n7=np.arange(10,20,2)
print(n7)

[10 12 14 16 18]


initializ numpy array with random number

In [63]:
n8=np.random.randint(10,30,6)
print(n8)

[12 25 10 26 12 29]


checking the shape of numpy array

In [64]:
print(n2.shape)

(2, 3)


In [65]:
n2.shape=(3,2)
print(n2)

[[10 20]
 [30 40]
 [50 60]]


In [66]:
n9=np.array([[10,20,30,40],
            [50,60,70,80],
            [10,40,80,90]])
n10=np.array([[10,40,80,90],
            [50,60,70,80],
            [10,20,30,40]])
print(n9)
print(n10)

[[10 20 30 40]
 [50 60 70 80]
 [10 40 80 90]]
[[10 40 80 90]
 [50 60 70 80]
 [10 20 30 40]]


In [67]:
np.vstack((n9,n10))

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [10, 40, 80, 90],
       [10, 40, 80, 90],
       [50, 60, 70, 80],
       [10, 20, 30, 40]])

In [68]:
np.hstack((n9,(n10)))

array([[10, 20, 30, 40, 10, 40, 80, 90],
       [50, 60, 70, 80, 50, 60, 70, 80],
       [10, 40, 80, 90, 10, 20, 30, 40]])

In [71]:
n11=np.array([10,20,30,40,50,60])
n12=np.array([10,20,30,40,80,90])
print(np.intersect1d(n11,n12))
print(np.setdiff1d(n11,n12))
print(np.setdiff1d(n12,n11))

[10 20 30 40]
[50 60]
[80 90]


Addition of numpy aaray

In [75]:
print(f"array-1 = {n11} array-2 = {n12}")
print(np.sum([n11,n12]))
print(np.sum([n11,n12],axis=0))
print(np.sum([n11,n12],axis=1))

array-1 = [10 20 30 40 50 60] array-2 = [10 20 30 40 80 90]
480
[ 20  40  60  80 130 150]
[210 270]


numpy array mathmatics

In [79]:
n13=np.array([10,20,30])
print(n13+1)
print(n13-1)
print(n13*2)
print(n13//2)

[11 21 31]
[ 9 19 29]
[20 40 60]
[ 5 10 15]


numpy math functions

In [83]:
print(n13)
print(np.min(n13))
print(np.median(n13))
print(np.std(n13))

[10 20 30 40]
10
25.0
11.180339887498949


numpy save and load

In [85]:
np.save('my_numpy',n13)
n14=np.load('my_numpy.npy')
print(n14)

[10 20 30 40]
